### ISSUE TITLE
[BUG] 64 char limit error hit when entries are > 64 char

### ISSUE THREAD

**Issue by vishinde** [GoogleCloudPlatform/datacatalog-connectors-hive#25]
**What happened**:
Entries which are greater than 64 char limit, error when tried to insert using connector

**What you expected to happen**:
Entries > 64 characters be seamlessly inserted in data catalog

**How to reproduce it (as minimally and precisely as possible)**:
have a table name long enough > 64 char and run the connector

**Anything else we need to know?**:

**Comment by mesmacosta** [comment]
Thanks @vishinde for filling this.
